name: Proxy Updater

on:
  schedule:
    - cron: "0 */2 * * *"

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3

      - run: rm *.txt -rfv
      - name: start proxy scraper
        run: |
          cd .github/workflows
          npm ci
          node index.js
      - name: generating README.md
        run: |
          echo -e "<div align=\"center\">\n" > README.md
          echo -e "# proxy-list\n" >> README.md
          echo -e "  [![zevtyardt - proxy-list](https://img.shields.io/static/v1?label=tahaluindo&message=proxy-list&color=blue&logo=github)](https://github.com/tahaluindo/proxy-list \"Go to GitHub repo\")" >> README.md
          echo -e "  [![stars - proxy-list](https://img.shields.io/github/stars/Itsmeafriliyan/proxy-list?style=social)](https://github.com/zevtyardt/proxy-list)" >> README.md
          echo -e "  [![forks - proxy-list](https://img.shields.io/github/forks/Itsmeafriliyan/proxy-list?style=social)](https://github.com/zevtyardt/proxy-list)\n" >> README.md

          echo -e "  [![Proxy Updater](https://github.com/Itsmeafriliyan/proxy-list/workflows/Proxy%20Updater/badge.svg)](https://github.com/zevtyardt/proxy-list/actions?query=workflow:\"Proxy+Updater\")" >> README.md
          echo -e "  ![GitHub repo size](https://img.shields.io/github/repo-size/Itsmeafriliyan/proxy-list)" >> README.md
          echo -e "  [![GitHub commit activity](https://img.shields.io/github/commit-activity/m/Itsmeafriliyan/proxy-list?logo=commits)](https://github.com/zevtyardt/proxy-list/commits/main)" >> README.md

          echo -e "\n</div>\n" >> README.md

          echo -e "  Ini Adalah Repository Yang Saya Buat Untuk Mempermudah Saya Dan Mungkin Juga Kalian Dalam Mencari Sebuah Proxy.\n" >> README.md
          echo -e "  - **Jumlah Proxy:** ±$(cat all.txt | wc -l)" >> README.md
          echo -e "  - **Terakhir Di Update:** $(TZ=Asia/Jakarta date +'%a, %d %b %y %T %Z')\n" >> README.md

          echo -e "# Unduh" >> README.md
          echo -e "  Salin Dan Tempel Salah Satu Kode Di Bawah Ke Terminal" >> README.md

          for file in *.txt;
          do
            echo -e "  - **$(echo $file | cut -d'.' -f1 | tr 'a-z' 'A-Z')** ($(cat $file | wc -l))" >> README.md
            echo -e "    \`\`\`bash" >> README.md
            echo -e "    curl https://raw.githubusercontent.com/zevtyardt/proxy-list/main/$file -o $file" >> README.md
            echo -e "    \`\`\`" >> README.md
          done

          echo -e "\n# TODO" >> README.md
          echo -e "  - [x] Hapus Folder *csv/*" >> README.md
          echo -e "  - [x] Sortir Proxy Menjadi 3 Bagian, HTTP/SOCKS4/SOCKS5" >> README.md
          echo -e "  - [ ] Cek Apakah Proxy Berfungsi Atau Tidak" >> README.md

          echo -e "\n# Catatan" >> README.md
          echo -e "> Jangan Lupa Kasih ⭐ Terus *Fork* Sama *Follow* Juga Kalau Perlu" >> README.md

      - name: start commit
        run: |
          git config --local user.name ${{ secrets.name }}
          # git config --local user.email ${{ secrets.email }}
          git status
          git add *.txt README.md
          git commit -m "update: $(cat all.txt | wc -l) proxies"
      - name: push changes
        uses: ad-m/github-push-action@master
        with: 
         github_token: ${{ secrets.GH_TOKEN }}
         force: true
